### ISSUE TITLE
UPDATED_DOMAINS Failing

### ISSUE THREAD

**Issue by gintechsystems** [BirgerK/docker-apache-letsencrypt#10]
When I try to updated my domains I am receiving the following message:

docker exec -it apache-ssl /run_letsencrypt.sh --domains $UPDATED_DOMAINS

Using Let's Encrypt Production environment...

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator apache, Installer apache

Obtaining a new certificate

An unexpected error occurred: The request message was malformed :: Error creating new order :: Invalid character in DNS name

Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by BirgerK** [comment]
Thanks for your issue.

First: has the variable `UPDATED_DOMAINS` a value? Or is it empty?

Second: what's the content of ` /var/log/letsencrypt`

**Comment by gintechsystems** [comment]
I did update the value. There was no content in that folder, I will try again and see though.

**Comment by gintechsystems** [comment]
The content folder is empty and seems to be why it is failing. I don't have much time right now to investigate this to much, so I assume if you tested this based on your response (that folder should have content and the updated_domains has a value is working) then all seems well..
