### ISSUE TITLE
remove fail2ban from image

### ISSUE THREAD

**Issue by Frankkkkk** [BirgerK/docker-apache-letsencrypt#4]
I don't really see the advantage of having fail2ban installed on this image. Following docker principles, it should be removed and put on another image.

Thanks,

Nice work, BTW

**Comment by BirgerK** [comment]
Yeah, you're right. I included it for myself. I didn't think of someone else would use this image! ;-)

I'll remove fail2ban from this when I got some time for it. You'll see progress in this issue if it happens.

**Comment by BirgerK** [comment]
Done! :)
