### ISSUE TITLE
Letsencrypt error on startup

### ISSUE THREAD

**Issue by loitly** [BirgerK/docker-apache-letsencrypt#6]
Hi,
Great work on this image.  I've been using it for months.  However, after my latest pull to fix the crontab problem,  I am getting this error : Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Do you have any ideas on how it can be fixed?  Thanks for your help.

**Comment by BirgerK** [comment]
Hi,

this looks like a build-in issue which letsencrypt has already solved: https://github.com/certbot/certbot/issues/5405

I can't reproduce this error on my own instance which is running letsencrypt in version `0.4.1`.  
The latest image version has also letsencrypt `0.4.1`.

Maybe you're a pull away from fixing this? If this doesn't work: which letsencrypt version has your image? (`letsencrypt --version`)

**Comment by BirgerK** [comment]
Seems like version 0.4.1 is pretty old. I pushed an update to the current certbot version. After the build is done (in maybe 10 minutes) please give it a try.

**Comment by loitly** [comment]
I got your new version.  There's still a couple of issues I noticed.

### crontab:
-  Hour part is wrong.  it should be between 0-23.  I think you want to say once every 3 days?  * * */3 * *
-  Command is also wrong, since it should be using certbot now.
-  Crontab is probably not needed since certbot for this version of ubuntu automatically setup cron job for renewal.
 

### VirtualHost:
-  certbot fail to run during start up because there's no VirtualHost matching the given domains.  I can't find where in your dockfile a VirtualHost is created.

**Comment by BirgerK** [comment]
Thanks for that.

The image does now use the crontab-command which certbot installs. It's pushed and needs some time for building.

There's no virtualhost provided in this image. It's a default apache installed, so virtualhosts can be placed in `/etc/apache2/sites-enabled`

**Comment by BirgerK** [comment]
I guess it's closed. If this issue still exists, please respond to this. :)
